---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Remya-project-cluster # name of cluster
  region: ap-south-1
  version: "1.24" # kubernetes version
vpc: # Refer: https://github.com/weaveworks/eksctl/blob/main/examples/04-existing-vpc.yaml
  id: "vpc-04c0abbbc0d0df7b8"
  subnets:
    public:
      public-subnet-1a:
        id: "subnet-05b29a9846842e193"
        az: "ap-south-1a"
      public-subnet-1b:
        id: "subnet-06629d9869448944d"
        az: "ap-south-1b"
    private:
      private-subnet-1a:
        id: "subnet-0141d101592969278"
        az: "ap-south-1a"
      private-subnet-1b:
        id: "subnet-05986c328510251fe"
        az: "ap-south-1b"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  nat:
    gateway: Disable # disable since already created

iam: # Refer: https://eksctl.io/usage/iamserviceaccounts/
  withOIDC: true
  serviceAccounts: # pre-including some common iamserviceaccounts
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true

nodeGroups: # Refer: https://github.com/weaveworks/eksctl/blob/main/examples/05-advanced-nodegroups.yaml
  - name: private-1a
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true" # tag is needed for cluster autoscaler. Refer: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
      k8s.io/cluster-autoscaler/Remya-project-cluster: "shared" # cluster name tag is optional in latest versions of EKS
    instancesDistribution:
      instanceTypes:
        - t3a.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    privateNetworking: true # include only in private subnet
    subnets:
      - private-subnet-1a # 1 AZ is enough for testing
  - name: public-1a
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/Remya-project-cluster: "shared"
    instancesDistribution:
      instanceTypes:
        - t3a.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 5
    subnets:
      - public-subnet-1a
